version: '3.8'

services:
  postgres-ticket:
    image: postgres:15
    container_name: postgres-ticket
    environment:
      POSTGRES_DB: Ticket_DB
      POSTGRES_USER: Dmitry
      POSTGRES_PASSWORD: qweqwe
    ports:
      - "5432:5432"
    networks:
      - backend
  postgres-admin:
    image: postgres:15
    container_name: postgres-admin
    environment:
      POSTGRES_DB: Admin
      POSTGRES_USER: Dmitry
      POSTGRES_PASSWORD: qweqwe
    ports:
      - "5433:5432" 
    networks:
      - backend

  postgres-book:
    image: postgres:15
    container_name: postgres-book
    environment:
      POSTGRES_DB: Book
      POSTGRES_USER: Dmitry
      POSTGRES_PASSWORD: qweqwe
    ports:
      - "5434:5432"
    networks:
      - backend

  consul:
    image: consul:1.15
    container_name: dev-consul
    ports:
      - "8500:8500"         # Consul UI
      - "8600:8600/udp"     # DNS
    command: agent -dev -client=0.0.0.0
    networks:
      - backend

  user-service-1:
    build:
      context: ./Users
    image: user-service:latest
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/Ticket_DB
      - SPRING_DATASOURCE_USERNAME=Dmitry
      - SPRING_DATASOURCE_PASSWORD=qweqwe
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-1:9092,kafka-2:9092,kafka-3:9092
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - consul
    networks:
      - backend

  user-service-2:
    build:
      context: ./Users
    image: user-service:latest
    container_name: user-service-1
    ports:
      - "8083:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/Ticket_DB
      - SPRING_DATASOURCE_USERNAME=Dmitry
      - SPRING_DATASOURCE_PASSWORD=qweqwe
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-1:9092,kafka-2:9092,kafka-3:9092
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - consul
    networks:
      - backend

  admin-service:
    build:
      context: ./Admin
    image: admin-service:latest
    container_name: admin-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/Flight
      - SPRING_DATASOURCE_USERNAME=Dmitry
      - SPRING_DATASOURCE_PASSWORD=qweqwe
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
    depends_on:
      - consul
    networks:
      - backend

  gateway-service:
    build:
      context: ./ApiGateway
    container_name: gateway-service
    ports:
      - "8888:8888"
    depends_on:
      - consul
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
    networks:
      - backend

  book-service:
    build:
      context: ./Book
    image: book-service:latest
    container_name: book-service
    ports:
      - "8091:8091"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/Book
      - SPRING_DATASOURCE_USERNAME=Dmitry
      - SPRING_DATASOURCE_PASSWORD=qweqwe
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
    depends_on:
      - consul
    networks:
      - backend

  kafka-1:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"     # основной порт для клиентов
      - "9093:9093"     # контроллер
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=WnLkTHhkQaiJbwP8FClPhw
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://:29092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka-1:9092,EXTERNAL://localhost:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
    volumes:
      - ./data/kafka-1:/var/lib/kafka/data/server-1
    networks:
      - backend


  kafka-2:
    image: bitnami/kafka:latest
    ports:
      - "9094:9092"    # пробросим 9092 контейнера на 9094 хоста
      - "9095:9093"    # контроллер
    environment:
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_KRAFT_CLUSTER_ID=WnLkTHhkQaiJbwP8FClPhw
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://:29094,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka-2:9092,EXTERNAL://localhost:29094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
    volumes:
      - ./data/kafka-2:/var/lib/kafka/data/server-2
    networks:
      - backend

  kafka-3:
    image: bitnami/kafka:latest
    ports:
      - "9096:9092"    # пробросим 9092 контейнера на 9096 хоста
      - "9097:9093"    # контроллер
    environment:
      - KAFKA_CFG_NODE_ID=3
      - KAFKA_KRAFT_CLUSTER_ID=WnLkTHhkQaiJbwP8FClPhw
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://:29096,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka-3:9092,EXTERNAL://localhost:29096
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
    volumes:
      - ./data/kafka-3:/var/lib/kafka/data/server-3
    networks:
      - backend
networks:
  backend:
    driver: bridge

    