version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: dev-postgres
    environment:
      POSTGRES_DB: Ticket_DB
      POSTGRES_USER: Dmitry
      POSTGRES_PASSWORD: qweqwe
    ports:
      - "5432:5432"
    networks:
      - backend
  consul:
    image: consul:1.15
    container_name: dev-consul
    ports:
      - "8500:8500"         # Consul UI
      - "8600:8600/udp"     # DNS
    command: agent -dev -client=0.0.0.0
    networks:
      - backend

  user-service:
    build:
      context: ./Users
    image: user-service:latest
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/Ticket_DB
      - SPRING_DATASOURCE_USERNAME=Dmitry
      - SPRING_DATASOURCE_PASSWORD=qweqwe
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
    depends_on:
      - consul
    networks:
      - backend

  admin-service:
    build:
      context: ./Admin
    image: admin-service:latest
    container_name: admin-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/Ticket_DB
      - SPRING_DATASOURCE_USERNAME=Dmitry
      - SPRING_DATASOURCE_PASSWORD=qweqwe
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
    depends_on:
      - consul
    networks:
      - backend

networks:
  backend:
    driver: bridge