# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/Ticket_DB
spring.datasource.username=Dmitry
spring.datasource.password=qweqwe
spring.jpa.hibernate.ddl-auto=none

# Kafka
spring.kafka.bootstrap-servers=localhost:9092,localhost:9094,localhost:9096
spring.kafka.producer.properties.enable.idempotence=false

# Security
spring.security.user.name=user
spring.security.user.password=qweqwe
logging.level.org.springframework.security=${SPRING_SECURITY_LOG_LEVEL:TRACE}
