# Database
spring.datasource.url=jdbc:postgresql://postgres-book:5432/Ticket_DB
spring.datasource.username=Dmitry
spring.datasource.password=qweqwe
spring.jpa.hibernate.ddl-auto=none

# Kafka
spring.kafka.bootstrap-servers=kafka-1:9092,kafka-2:9092,kafka-3:9092
spring.kafka.producer.properties.enable.idempotence=true