spring.datasource.url=jdbc:postgresql://postgres-book:5432:5432/Book
spring.datasource.username=Dmitry
spring.datasource.password=qweqwe
spring.jpa.hibernate.ddl-auto=none


spring.kafka.consumer.bootstrap-servers=kafka-1:9092,kafka-2:9092,kafka-3:9092

