spring.datasource.url=jdbc:postgresql://localhost:5432/Book
spring.datasource.username=Dmitry
spring.datasource.password=qweqwe
spring.jpa.hibernate.ddl-auto=none


spring.kafka.consumer.bootstrap-servers=localhost:9092,localhost:9094,localhost:9096

