CREATE TABLE users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name   VARCHAR(255)                            NOT NULL,
    second_name  VARCHAR(255)                            NOT NULL,
    password     VARCHAR(255)                            NOT NULL,
    age          INTEGER                                 NOT NULL,
    email        VARCHAR(255),
    phone_number VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_phonenumber UNIQUE (phone_number);